### ISSUE TITLE
Core design progress metabug

### ISSUE THREAD

**Issue by S11001001** [ermine-language/ermine-scala-core#6]
This is probably out of date, but gives us a good idea of how far this got, and the general direction we'd want to go should we roll one from scratch.  It's from @joshcough .
- [x] Implement naive interpreter in the style of bound's example.
- [x] Add primitive/native function support.
- [x] Add simple example from bound.
- [x] Add examples for Data
- [x] Add examples for Dictionaries.
- [x] Add Show examples for Bool, Int and List
- [ ] Refactor primtive function support later on, because it's hacked in.
- [ ] Read (and understand) Spineless Tagless G-Machine paper
- [ ] Implement STG style interpreter (later).
